In [1]:
import sys
sys.path.append("..")
from lib.llm.llm_client import timed_completion, strip_thinking, MODEL, MODEL_N

In [2]:
extra = {"chat_template_kwargs": {"enable_thinking": False}} if MODEL_N == 1 else {}

response, latency_ms = timed_completion(
    messages=[{"role": "user", "content": "Say hello."}],
    model=MODEL,
    n=MODEL_N,
    extra_body=extra,
)
print(strip_thinking(response.choices[0].message.content))
print(f"Latency: {latency_ms:.0f} ms")

Hello! How can I help you today?
Latency: 903 ms

In [3]:
import pandas as pd


df = pd.read_csv("../datasets/ESGenius_w_ref_1136q.csv")
df.head()

,query_id,new_id,query,answer,A,B,C,D,Z,ref_page,ref_doc,source_text
0,831,1,"According to the IPCC AR6 Synthesis Report, wh...",A,Implementing targeted management strategies fo...,Failing to rebuild overexploited fisheries whi...,Limiting global warming but neglecting land re...,Prioritizing disaster risk management and earl...,Not sure,46,IPCC AR6 SYR.pdf,30 Summary for Policymakers Summary for Policy...
1,889,2,According to Climate Change 2023 — Synthesis R...,B,The geographical patterns of climatic impacts ...,Geographical patterns of climatic impacts for ...,The timing of reaching a specific GWL determin...,Global warming levels are defined exclusively ...,Not sure,80-81,IPCC AR6 SYR.pdf,64 Section 2 Section 1Section 2Global Warming ...
2,892,3,Which statement accurately reflects the relati...,C,High or very high confidence in attribution is...,The text explicitly states that medium confide...,Attribution of observed physical climate chang...,Increases in heavy precipitation and sea level...,Not sure,23,IPCC AR6 SYR.pdf,7 Summary for PolicymakersSummary for Policyma...
3,983,4,According to the Climate Change 2023 — Synthes...,D,Europe,Small Islands,North America,Asia,Not sure,92,IPCC AR6 SYR.pdf,76 Section 3 Section 1Section 3011.5234 011.52...
4,1077,5,According to the Climate Change 2023 — Synthes...,A,"Early warning systems, flood-proofing of build...","Afforestation, reforestation, and levees.","Agroecological practices, disaster risk manage...","Heat Health Action Plans, vector-borne disease...",Not sure,72,IPCC AR6 SYR.pdf,"56 Section 2 Section 1Section 2wetlands, range..."

In [4]:
pertrubed_df = pd.read_csv("../datasets/esgenius_perturbed.csv")

pertrubed_df.head()

,query_id,new_id,query,answer,A,B,C,D,Z,ref_page,ref_doc,source_text,perturbation_type,perturbation_level
0,831,1,"According to the IPCC AR6 Synthesis Report, wh...",A,Implementing targeted management strategies fo...,Failing to rebuild overexploited fisheries whi...,Limiting global warming but neglecting land re...,Prioritizing disaster risk management and earl...,Not sure,46,IPCC AR6 SYR.pdf,30 Summary for Policymakers Summary for Policy...,none,0
1,831,1,"According to the IPCC AR6 Synthesis Report, wh...",A,Implementing targeted management strategies fo...,Failing to rebuild overexploited fisheries whi...,Limiting global warming but neglecting land re...,Prioritizing disaster risk management and earl...,Not sure,46,IPCC AR6 SYR.pdf,27.9 Summary for Policymakers Summary for Poli...,numeric,1
2,831,1,"According to the IPCC AR6 Synthesis Report, wh...",A,Implementing targeted management strategies fo...,Failing to rebuild overexploited fisheries whi...,Limiting global warming but neglecting land re...,Prioritizing disaster risk management and earl...,Not sure,46,IPCC AR6 SYR.pdf,30 Summary for Policymakers Summary for Policy...,missing,1
3,831,1,"According to the IPCC AR6 Synthesis Report, wh...",A,Failing to rebuild overexploited fisheries whi...,Implementing targeted management strategies fo...,Limiting global warming but neglecting land re...,Prioritizing disaster risk management and earl...,Not sure,46,IPCC AR6 SYR.pdf,30 Summary for Policymakers Summary for Policy...,label,1
4,831,1,"According to the IPCC AR6 Synthesis Report, wh...",A,Implementing targeted management strategies fo...,Failing to rebuild overexploited fisheries whi...,Limiting global warming but neglecting land re...,Prioritizing disaster risk management and earl...,Not sure,46,IPCC AR6 SYR.pdf,Land restoration contributes to climate change...,format,1

In [ ]:
df.dtypes

query_id       int64
new_id         int64
query            str
answer           str
A                str
B                str
C                str
D                str
Z                str
ref_page         str
ref_doc          str
source_text      str
dtype: object